//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockId { get; set; }
        public int NumberCount { get; set; }
        public System.DateTime CurrentDate { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int InventoryId { get; set; }
        public bool IsPurchase { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public string BarCode { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
